name:                example-etl
version:             0.1.0.0
github:              "mjgajda/example-etl"
license:             BSD3
author:              "Michał J. Gajda"
maintainer:          "mjgajda@migamake.com"
copyright:           "Michał J. Gajda &#39;2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mjgajda/example-etl#readme>

dependencies:
- base >= 4.7 && < 5
- json-alt
- aeson
- hsparklines
- Chart
- Chart-cairo
- vinyl
- foldl
- Frames
- pipes

library:
  source-dirs: src

executables:
  example-etl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - example-etl

tests:
  example-etl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - example-etl
